[package]
name = "respcas"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "A Redis-compatible server using cas-storage as backend"

# Expose the modules as a library
[lib]
name = "respcas"
path = "src/lib.rs"

[[bin]]
name = "respcas"
path = "src/main.rs"

[dependencies]
cas-storage = { path = "../cas-storage" }
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
redis-protocol = { version = "6.0.0", features = ["bytes"] }
atoi = "3.1.0"
thiserror = "2.0.19"
md-5 = { workspace = true }
serde = { workspace = true }
rmp-serde = "1.3.1"

[dev-dependencies]
tempfile = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
rand = { workspace = true }
redis = { version = "1.5.0" }
